### ISSUE TITLE
Copy shortcut - does not work

### ISSUE THREAD

**Issue by vincentkam** [mtusnio/chinesedict#1]
Steps to reproduce: Enable the extension, and hover over any Chinese word, and press "C". 
Expected behavior: The text in the pop up (including the Mandarin zhuyhin and Cantonese jyutping) should be copied to the clipboard.
Actual behavior: The clipboard contents does not change

Debugging with Edge, I see the following:
```
Uncaught TypeError: savedSearchResults[i].slice is not a function
    at getTextForClipboard (content.js:785:41)
    at HTMLDocument.onKeyDown (content.js:145:29)
```
Best guess:
Looking at the OG extension "zhongwen" I see the following:
https://github.com/cschiller/zhongwen/blob/master/content.js#L926
```
texts[i] = [entry[2], entry[1], p[1], translation, entry[3]];
// ...
 savedSearchResults = texts;
```
which I think creates an array that slice can be called on

**Comment by mtusnio** [comment]
Hello @vincentkam 

Apologies for spotting this just now, I must've lost it in a flurry of work-related notifications.

I will have a look at the PR soon and see about releasing an update :)

**Comment by vincentkam** [comment]
:) Having too many work-related notifications is 100% relatable (as you can tell from my own delayed response!)

**Comment by mtusnio** [comment]
I got some time this Christmas to update the dictionary and push a new release for a Google Store review, hopefully within a few days it will be ready to release!
